#!/usr/bin/env python

from distutils.core import setup, Command
from distutils.spawn import find_executable
import sh
import os

protoc = find_executable("protoc")


class BuildPbfCommand(Command):
    description = "build protocol buffer files"
    user_options = []
    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def run(self):
        os.system('{protoc} -Ichaos-proto --python_out=kirin chaos-proto/*.proto'.format(protoc=protoc))
        os.system('{protoc} -Inavitia-proto --python_out=kirin navitia-proto/*.proto'.format(protoc=protoc))


class BuildVersionCommand(Command):
    description = "build version file from git"
    user_options = []
    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def run(self):
        git = sh.git.bake()
        filename = os.path.dirname(os.path.realpath("__file__")) + '/kirin/version.py'
        res = git.describe()
        with open(filename, 'w') as file:
            file.write("""#file generated by setup.py build_version don't modify directly!
version = '{}'\n""".format(res.stdout.strip('\n')))

setup(
    name='kirin',
    cmdclass={'build_pbf': BuildPbfCommand, 'build_version': BuildVersionCommand}
)

