"""Add Raw XML table

Revision ID: 1e19f2d53b4a
Revises: 434d1e68281b
Create Date: 2015-09-06 16:03:31.739685

"""

# revision identifiers, used by Alembic.
revision = '1e19f2d53b4a'
down_revision = '434d1e68281b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_ire',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('raw_xml', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'real_time_update', sa.Column('raw_ire_id', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'real_time_update', 'raw_ire', ['raw_ire_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'real_time_update', type_='foreignkey')
    op.drop_column(u'real_time_update', 'raw_ire_id')
    op.drop_table('raw_ire')
    ### end Alembic commands ###
